---
title: "baseline_data_clean"
author: "Madeline Berger"
date: "11/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(stringr)

lat_lon <- read.csv("lag_lng_allbaseline.csv")

head(lat_lon$latitude[1])

x = lat_lon$latitude[1]

#create a unique identifier for each group of vertices by merging the plot id column with the farmer id to create a new id

lat_lon_id <- lat_lon %>%
  mutate(unique_id=paste(substr(plot_id, 2, 2), a_hhid))
  

lat_lon_id$unique_id <- gsub(" ", "", lat_lon_id$unique_id, fixed = TRUE)
  #unite("unique_id", plot_id, a_hhid, remove = FALSE)

#the goal is to:
#loop over all the different of a_hhid and for each one, filter by "a_hhid = this" 
#and then pull out lat and longitude 
#turn into matrix 
```

```{r}

#all ids
id_vec <- unique(lat_lon_id$unique_id) #make a list of all the values in unique_id column, can this be numeric?

#for testing
df_short <- lat_lon_id %>% 
   filter(unique_id == "110010033" | unique_id == "110010039" | unique_id == "110010075") 



#make a shorter list for the test set
id_vec_test <- unique(df_short$unique_id)
poly_list <- vector("list", length(id_vec_test))

########################################################

#making matrices and testing for closure

 id = id_vec[i]
  
df <- lat_lon_id %>% 
    filter(unique_id == id) %>% 
    select(longitude, latitude) %>% 
    as.matrix

line_sf <- st_linestring(df)

plot(line_sf)

#check whether the first and last rows are the same point: 

df[1, ] == df[nrow(df), ]

#bind the matrix with its own first row to close it

df_closed <- rbind(df, df[1, ])

#check again if the first and last rows are closed

df_closed[1, ] == df_closed[nrow(df_closed), ]

line_sf_closed <- st_linestring(df_closed)

plot(line_sf_closed)


#################################################

#method 2: I am trying to tell R to identify duplicates, and then move the duplicate to the final row

duplicated(df)

dup <- df[duplicated(df)] 

if(which(duplicated(df) != 1, nrow(df))) {
 
}
   


########################################################
  
df_test <- lat_lon_id %>% 
   filter(unique_id == "110010013") %>% 
    select(longitude, latitude) %>% 
    as.matrix


#y = df[1]
#z = df[9,2] #does it make a difference that this is a "named number"


#######################################################

for(i in seq_along(unique(lat_lon_id$unique_id))){
  #filter the df 
  id = id_vec[i]
  
  df <- lat_lon_id %>% 
    filter(unique_id == id) %>% 
    select(longitude, latitude) %>% 
    as.matrix
  #get the coodrinates
  #create the polygon, and add attributes
  poly <- st_sf(data.frame(unique_id = id, st_sfc(st_polygon(list(as.matrix(df))),crs = 4326)))
  
 
 if(i == 1) {
   poly_sf <- poly
 } else {
   poly_sf <- rbind(poly_sf, poly)
 }
 
}

#another idea to try: 

#polygon <- df %>%
  #st_as_sf(coords = c("lon", "lat"), crs = 4326) %>%
  #summarise(geometry = st_combine(geometry)) %>%
  #st_cast("POLYGON")
#polygon



#write_sf()



```

Bind poly_id, farmer id, and family id to poly_sf 

```{r}

#create table of IDs minus the lat lon data

info <- lat_lon_id[-c(4:5)]

info_short <- info %>% 
  filter(unique_id == "110010033" | unique_id == "110010039" | unique_id == "110010075")


#merge  

poly_complete <- merge(poly_sf, info_short, by = "unique_id")

#yay works! 

```




Writing out shapefiles and csv
```{r}
st_write(poly_complete, "test_2.shp")

#better if you could add a path, worry about this later


write_csv(lat_lon_id, "H:/punjab_project/punjab_project/ids.csv", col_names = TRUE)
```



Issue remaining - not all the first and last coordinates are the same! They have to be in order
